module config {
    export enum Scene {
        START,
        OPENING_SCENE,
        GRAVEYARD_1,
        GRAVEYARD_2,
        GRAVEYARD_3,
        GRAVEYARD_4,
        GRAVEYARD_5,
        GRAVEYARD_6,
        GRAVEYARD_7,
        GRAVEYARD_8,
        HOTEL_1,
        HOTEL_2,
        HOTEL_3,
        HOTEL_4,
        HOTEL_5,
        HOTEL_6,
        HOTEL_7,
        HOTEL_8,
        HOTEL_9,
        HOTEL_10,
        HOTEL_11,
        HOTEL_12,
        HOTEL_13,
        HOTEL_14,
        HOTEL_15,
        STAGE_PICKER,
        SHOP,
        OVER = -1
    }
}