var config;
(function (config) {
    var Scene;
    (function (Scene) {
        Scene[Scene["START"] = 0] = "START";
        Scene[Scene["OPENING_SCENE"] = 1] = "OPENING_SCENE";
        Scene[Scene["GRAVEYARD_1"] = 2] = "GRAVEYARD_1";
        Scene[Scene["GRAVEYARD_2"] = 3] = "GRAVEYARD_2";
        Scene[Scene["GRAVEYARD_3"] = 4] = "GRAVEYARD_3";
        Scene[Scene["GRAVEYARD_4"] = 5] = "GRAVEYARD_4";
        Scene[Scene["GRAVEYARD_5"] = 6] = "GRAVEYARD_5";
        Scene[Scene["GRAVEYARD_6"] = 7] = "GRAVEYARD_6";
        Scene[Scene["GRAVEYARD_7"] = 8] = "GRAVEYARD_7";
        Scene[Scene["GRAVEYARD_8"] = 9] = "GRAVEYARD_8";
        Scene[Scene["HOTEL_1"] = 10] = "HOTEL_1";
        Scene[Scene["HOTEL_2"] = 11] = "HOTEL_2";
        Scene[Scene["HOTEL_3"] = 12] = "HOTEL_3";
        Scene[Scene["HOTEL_4"] = 13] = "HOTEL_4";
        Scene[Scene["HOTEL_5"] = 14] = "HOTEL_5";
        Scene[Scene["HOTEL_6"] = 15] = "HOTEL_6";
        Scene[Scene["HOTEL_7"] = 16] = "HOTEL_7";
        Scene[Scene["HOTEL_8"] = 17] = "HOTEL_8";
        Scene[Scene["HOTEL_9"] = 18] = "HOTEL_9";
        Scene[Scene["HOTEL_10"] = 19] = "HOTEL_10";
        Scene[Scene["HOTEL_11"] = 20] = "HOTEL_11";
        Scene[Scene["HOTEL_12"] = 21] = "HOTEL_12";
        Scene[Scene["HOTEL_13"] = 22] = "HOTEL_13";
        Scene[Scene["HOTEL_14"] = 23] = "HOTEL_14";
        Scene[Scene["HOTEL_15"] = 24] = "HOTEL_15";
        Scene[Scene["MANSION_1"] = 25] = "MANSION_1";
        Scene[Scene["MANSION_2"] = 26] = "MANSION_2";
        Scene[Scene["MANSION_3"] = 27] = "MANSION_3";
        Scene[Scene["MANSION_4"] = 28] = "MANSION_4";
        Scene[Scene["MANSION_5"] = 29] = "MANSION_5";
        Scene[Scene["MANSION_6"] = 30] = "MANSION_6";
        Scene[Scene["MANSION_7"] = 31] = "MANSION_7";
        Scene[Scene["MANSION_8"] = 32] = "MANSION_8";
        Scene[Scene["MANSION_9"] = 33] = "MANSION_9";
        Scene[Scene["MANSION_10"] = 34] = "MANSION_10";
        Scene[Scene["MANSION_11"] = 35] = "MANSION_11";
        Scene[Scene["MANSION_12"] = 36] = "MANSION_12";
        Scene[Scene["MANSION_13"] = 37] = "MANSION_13";
        Scene[Scene["MANSION_14"] = 38] = "MANSION_14";
        Scene[Scene["MANSION_15"] = 39] = "MANSION_15";
        Scene[Scene["MANSION_16"] = 40] = "MANSION_16";
        Scene[Scene["MANSION_17"] = 41] = "MANSION_17";
        Scene[Scene["MANSION_18"] = 42] = "MANSION_18";
        Scene[Scene["STAGE_PICKER"] = 43] = "STAGE_PICKER";
        Scene[Scene["SHOP"] = 44] = "SHOP";
        Scene[Scene["OVER"] = -1] = "OVER";
    })(Scene = config.Scene || (config.Scene = {}));
})(config || (config = {}));
//# sourceMappingURL=scene.js.map